# Generated by Django 4.2.7 on 2023-11-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('quality', models.CharField(max_length=25)),
            ],
        ),
    ]
