# Generated by Django 4.2.7 on 2023-11-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='ipAddress',
            field=models.CharField(default='Null', max_length=25),
        ),
        migrations.AlterField(
            model_name='db',
            name='quality',
            field=models.CharField(default='Null', max_length=25),
        ),
        migrations.AlterField(
            model_name='db',
            name='title',
            field=models.CharField(default='Null', max_length=25),
        ),
        migrations.AlterField(
            model_name='db',
            name='type',
            field=models.CharField(default='Null', max_length=25),
        ),
        migrations.AlterField(
            model_name='db',
            name='url',
            field=models.CharField(default='Null', max_length=25),
        ),
    ]
