# Generated by Django 4.2.7 on 2023-11-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0002_alter_db_ipaddress_alter_db_quality_alter_db_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='stream',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='db',
            name='url',
            field=models.URLField(),
        ),
    ]
